# Generated by Django 5.0.6 on 2024-08-29 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_film_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='film',
            name='film_name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.CreateModel(
            name='FilmListRecommendation',
            fields=[
                ('list_id', models.AutoField(primary_key=True, serialize=False)),
                ('list_title', models.CharField(max_length=100, unique=True)),
                ('films', models.ManyToManyField(to='app1.film')),
            ],
        ),
    ]
