# Generated by Django 5.0.6 on 2024-09-09 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_user_alter_film_film_name_filmlistrecommendation'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='film_list_recommendations',
            field=models.ManyToManyField(to='app1.filmlistrecommendation'),
        ),
    ]
